//
// Created by volglizolic on 4/22/20.
//

#ifndef PERFORMANCE_COUNTERS_UTILS_HPC_UTILS_H
#define PERFORMANCE_COUNTERS_UTILS_HPC_UTILS_H

#include <sched.h>
#include <stdbool.h>


typedef unsigned int counter_id_t;
typedef unsigned int counter_selector_id_t;
typedef unsigned long long counter_value_t;

#if __riscv_xlen == 32
typedef unsigned int events_t;
typedef unsigned int event_class_mask_t;
#else
typedef unsigned long long events_t;
typedef unsigned long long event_class_t;
#endif


typedef struct {
    event_class_t event_class_mask;
    events_t events_mask;
    bool first_time;
} hpc_event_selector_t;

typedef struct {
    counter_selector_id_t selector_id;
    counter_id_t counter_id;
} hpc_counter_t;

typedef struct hpc_event_selector_set_internal_tt{
    struct hpc_event_selector_set_internal_tt *next;
    events_t events_mask;
    counter_id_t counter_id;
    cpu_set_t cpu_set;
} hpc_event_selector_set_internal_t;

typedef struct hpc_event_selector_set_tt{
    hpc_event_selector_set_internal_t *head;
    unsigned int available_counters;
    int no_available_counters;
} hpc_event_selector_set_t;

int init_event_selector(hpc_event_selector_t *hpc_event_selector);

int init_event_selector_set(hpc_event_selector_set_t* hpc_event_selector_set);
int add_event_selector(hpc_event_selector_set_t* hpc_event_selector_set,
        hpc_event_selector_t *hpc_event_selector, int counter_number, cpu_set_t* cpu_set);

int hpc_set_exception_taken_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_integer_load_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_integer_store_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_atomic_memory_operation_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_system_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_integer_arithmetic_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_conditional_branch_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_jal_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_jalr_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_integer_multiplication_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_integer_division_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_floating_point_load_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_floating_point_store_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_floating_point_addition_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_floating_point_multiplication_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_floating_point_fused_multiplication_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_floating_point_division_or_square_root_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_other_floating_point_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);

int hpc_set_load_use_interlock_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_long_latency_interlock_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_csr_read_interlock_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_instruction_cache_or_dtim_busy_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_data_cache_or_dtim_busy_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_branch_direction_misprediction_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_branch_jump_target_misprediction_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_pipeline_flush_from_csr_write_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_pipeline_flush_from_other_event_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_integer_multiplication_interlock_event(hpc_event_selector_t *hpc_event_mask);

int hpc_set_instruction_cache_miss_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_data_cache_miss_or_memory_mapped_io_access_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_data_cache_writeback_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_instruction_tlb_miss_event(hpc_event_selector_t *hpc_event_mask);
int hpc_set_data_tlb_miss_event(hpc_event_selector_t *hpc_event_mask);

int hpc_unset_exception_taken_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_integer_load_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_integer_store_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_atomic_memory_operation_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_system_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_integer_arithmetic_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_conditional_branch_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_jal_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_jalr_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_integer_multiplication_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_integer_division_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_floating_point_load_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_floating_point_store_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_floating_point_addition_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_floating_point_multiplication_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_floating_point_fused_multiplication_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_floating_point_division_or_square_root_retired_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_other_floating_point_instruction_retired_event(hpc_event_selector_t *hpc_event_mask);

int hpc_unset_load_use_interlock_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_long_latency_interlock_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_csr_read_interlock_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_instruction_cache_or_dtim_busy_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_data_cache_or_dtim_busy_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_branch_direction_misprediction_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_branch_jump_target_misprediction_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_pipeline_flush_from_csr_write_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_pipeline_flush_from_other_event_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_integer_multiplication_interlock_event(hpc_event_selector_t *hpc_event_mask);

int hpc_unset_instruction_cache_miss_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_data_cache_miss_or_memory_mapped_io_access_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_data_cache_writeback_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_instruction_tlb_miss_event(hpc_event_selector_t *hpc_event_mask);
int hpc_unset_data_tlb_miss_event(hpc_event_selector_t *hpc_event_mask);

int apply_event_selector(hpc_event_selector_t hpc_ev_sel, int counter);

#endif //PERFORMANCE_COUNTERS_UTILS_HPC_UTILS_H
