//
// Created by volglizolic on 4/23/20.
//

#ifndef PERFORMANCE_COUNTERS_UTILS_FU540_H
#define PERFORMANCE_COUNTERS_UTILS_FU540_H

#define STATIC_COUNTER_ENABLED
#define NUMBER_OF_COUNTERS 2
#define COUNTERS_MASK (0b11000)

#define EVENT_CLASS_MASK ( 0b11111111 )

#define INSTRUCTION_COMMIT_EVENT_CLASS ( 0u )

#define EXCEPTION_TAKEN_EVENT ( 1u << 8u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define INTEGER_LOAD_INSTRUCTION_RETIRED_EVENT ( 1u << 9u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define INTEGER_STORE_INSTRUCTION_RETIRED_EVENT ( 1u << 10u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define ATOMIC_MEMORY_OPERATION_RETIRED_EVENT ( 1u << 11u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define SYSTEM_INSTRUCTION_RETIRED_EVENT ( 1u << 12u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define INTEGER_ARITHMETIC_INSTRUCTION_RETIRED_EVENT ( 1u << 13u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define CONDITIONAL_BRANCH_RETIRED_EVENT ( 1u << 14u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define JAL_INSTRUCTION_RETIRED_EVENT ( 1u << 15u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define JALR_INSTRUCTION_RETIRED_EVENT ( 1u << 16u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define INTEGER_MULTIPLICATION_INSTRUCTION_RETIRED_EVENT ( 1u << 17u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define INTEGER_DIVISION_INSTRUCTION_RETIRED_EVENT ( 1u << 18u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define FLOATING_POINT_LOAD_INSTRUCTION_RETIRED ( 1u << 19u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define FLOATING_POINT_STORE_INSTRUCTION_RETIRED ( 1u << 20u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define FLOATING_POINT_ADDITION_RETIRED ( 1u << 21u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define FLOATING_POINT_MULTIPLICATION_RETIRED ( 1u << 22u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define FLOATING_POINT_FUSED_MULTIPLY_ADD_RETIRED ( 1u << 23u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define FLOATING_POINT_DIVISION_OR_SQUARE_ROOT_RETIRED ( 1u << 24u | INSTRUCTION_COMMIT_EVENT_CLASS )
#define OTHER_FLOATING_POINT_INSTRUCTION_RETIRED ( 1u << 25u | INSTRUCTION_COMMIT_EVENT_CLASS )


#define MICROARCHITECTURAL_EVENT_CLASS ( 1u )

#define LOAD_USE_INTERLOCK ( 1u << 8u | MICROARCHITECTURAL_EVENT_CLASS )
#define LONG_LATENCY_INTERLOCK ( 1u << 9u | MICROARCHITECTURAL_EVENT_CLASS )
#define CSR_READ_INTERLOCK ( 1u << 10u | MICROARCHITECTURAL_EVENT_CLASS )
#define INSTRUCTION_CACHE_OR_DTIM_BUSY ( 1u << 11u | MICROARCHITECTURAL_EVENT_CLASS )
#define DATA_CACHE_OR_DTIM_BUSY ( 1u << 12u | MICROARCHITECTURAL_EVENT_CLASS )
#define BRANCH_DIRECTION_MISPREDICTION ( 1u << 13u | MICROARCHITECTURAL_EVENT_CLASS )
#define BRANCH_JUMP_TARGET_MISPREDICTION ( 1u << 14u | MICROARCHITECTURAL_EVENT_CLASS )
#define PIPELINE_FLUSH_FROM_CSR_WRITE ( 1u << 15u | MICROARCHITECTURAL_EVENT_CLASS )
#define PIPELINE_FLUSH_FROM_OTHER_EVENT ( 1u << 16u | MICROARCHITECTURAL_EVENT_CLASS )
#define INTEGER_MULTIPLICATION_INTERLOCK ( 1u << 17u | MICROARCHITECTURAL_EVENT_CLASS )
#define FLOATING_POINT_INTERLOCK ( 1u << 18u | MICROARCHITECTURAL_EVENT_CLASS )


#define MEMORY_SYSTEM_EVENT_CLASS ( 2u )

#define INSTRUCTION_CACHE_MISS ( 1u << 8u | MEMORY_SYSTEM_EVENT_CLASS )
#define DATA_CACHE_MISS_OR_MEMORY_MAPPED_IO_ACCESS ( 1u << 9u | MEMORY_SYSTEM_EVENT_CLASS )
#define DATA_CACHE_WRITEBACK ( 1u << 10u | MEMORY_SYSTEM_EVENT_CLASS )
#define INSTRUCTION_TLB_MISS ( 1u << 11u | MEMORY_SYSTEM_EVENT_CLASS )
#define DATA_TLB_MISS ( 1u << 12u | MEMORY_SYSTEM_EVENT_CLASS )

#endif //PERFORMANCE_COUNTERS_UTILS_FU540_H




